name: dataset-documentation-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python = 3.12.0
  - ipykernel = 6.29.5
  - openpyxl = 3.1.5
  - ipywidgets
  - pip
  - pip:
      - pandas == 2.2.3
      - matplotlib == 3.10.0
      - seaborn == 0.13.2
      - sentence-transformers == 3.3.1
      - PyGithub == 2.5.0
